services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: demo-nextjs-dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: demo-nextjs
    ports:
      - "3005:3000"
    env_file:
      - .env

volumes:
  node_modules: